language: cpp

addons:
  apt:
    packages:
      - swig
      - python-dev
      - python3-dev
      - libboost-date-time1.55-dev # boost libs necessary for MMCore
      - libboost-system1.55-dev
      - libboost-thread1.55-dev
      - libfreeimageplus-dev # some additional libs necessary for additional device adapters
      - libhidapi-dev
      - libdc1394-22-dev
      - libgphoto2-dev
      - libusb-dev
      - libopencv-dev
    sources:
      - boost-latest

script:
  - ./autogen.sh
  - mkdir -p ImageJ/jars
  - mvn org.apache.maven.plugins:maven-dependency-plugin:2.4:get -Dartifact=net.imagej:ij:LATEST -DrepoUrl=https://repo.maven.apache.org/maven2/ -Ddest=ImageJ/jars/ij.jar
  - ./configure --enable-imagej-plugin=`pwd`/ImageJ
  - make fetchdeps
  - make
  - make install
  - cp bindist/any-platform/MMConfig_demo.cfg ImageJ/
  - find `pwd`/ImageJ
