image: Visual Studio 2015
clone_depth: 5

before_build:
  - cmd: echo "..."
#  - cmd: "\"%VS100COMNTOOLS%\\vcupgrade\" /overwrite some.vcproj"

platform:
  - x86
  - x64

configuration: Release

build:
  parallel: true
  project: DeviceAdapters/SimulatingCamera/SimulatingCamera.vcxproj

after_build:
  - cmd: dir /s
#  - cmd: 7z a result.zip ...

#artifacts:
#  - path: result.zip

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

